pipeline {
  agent any

  stages {
    
    stage("ls") {
      steps {
        sh 'ls -la '
      }
    }
    stage("Test pull image") {
     steps {

       sh 'docker pull nginx'
     }
    }
  }
}